//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_FloodedArea : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean FloodedArea_Walk
        {
            get
            {
                return SteamVR_Actions.floodedArea_FloodedArea_Walk;
            }
        }
        
        public virtual SteamVR_Action_Boolean FloodedArea_Jump
        {
            get
            {
                return SteamVR_Actions.floodedArea_FloodedArea_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean UI_Click
        {
            get
            {
                return SteamVR_Actions.floodedArea_UI_Click;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuBtnClick
        {
            get
            {
                return SteamVR_Actions.floodedArea_MenuBtnClick;
            }
        }
    }
}
